# Generated by Django 2.1.1 on 2018-10-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='card.Status'),
        ),
    ]
