# Generated by Django 2.1.1 on 2018-10-02 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_card_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='card.Status'),
        ),
    ]
