# Generated by Django 2.1.1 on 2018-10-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_card_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='role',
            field=models.ManyToManyField(null=True, to='card.Role'),
        ),
    ]
